# API keys for external services
api_keys:
  # Required: Your key for the YouTube Data API
  youtube_api: "AIzaSyBAmGmUB5hQh9FO-DxFwLyVznT_QFxDsK0"

# Path where the output files will be saved.
# The folder should exist.
output_directory: "outputs/"

# List of content sources.
# 'type' must be either 'analysis' or 'datapoint'.
# 'format' must be either 'youtube' or 'webpage'.
sources:
  - name: "Geopolitical Economy Report"
    url: "https://www.youtube.com/@GeopoliticalEconomyReport/videos"
    type: "analysis"
    format: "youtube"
  - name: "Breakthrough News"
    url: "https://www.youtube.com/@BreakThroughNews"
    type: "analysis"
    format: "youtube"
  - name: "The Socialist Program"
    url: "https://www.patreon.com/collection/877189?view=condensed"
    type: "analysis"
    format: "webpage"
  - name: "Democracy at Work"
    url: "https://www.youtube.com/@democracyatwrk"
    type: "analysis"
    format: "youtube"
  - name: "Richard D Wolff"
    url: "https://m.youtube.com/@RichardDWolff"
    type: "analysis"
    format: "youtube"
  - name: "Michael Robets Blog"
    url: "https://thenextrecession.wordpress.com/blog"
    type: "analysis"
    format: "webpage"
  - name: "Tricontinental - Newsletters"
    url: "https://thetricontinental.org/newsletter/"
    type: "analysis"
    format: "webpage"
  - name: "Tricontinental - Dossiers"
    url: "https://thetricontinental.org/dossier/"
    type: "analysis"
    format: "webpage"
  - name: "Tricontinental - Wenhua Zongheng"
    url: "https://thetricontinental.org/wenhua-zongheng/"
    type: "analysis"
    format: "webpage"
  - name: "Progressive International"
    url: "https://progressive.international"
    type: "analysis"
    format: "webpage"
  - name: "Jacobin"
    url: "https://www.youtube.com/@JacobinMag"
    type: "analysis"
    format: "youtube"
  - name: "India & Global Left"
    url: "https://www.youtube.com/@IndiaGlobalLeft/videos"
    type: "analysis"
    format: "youtube"
  - name: "First Thought"
    url: "https://www.youtube.com/@firstthoughtnews"
    type: "analysis"
    format: "youtube"
  - name: "Second Thought"
    url: "https://www.youtube.com/@SecondThought"
    type: "analysis"
    format: "youtube"
  - name: "Tarik Cyril Amar"
    url: "https://tarikcyrilamar.substack.com/archive"
    type: "analysis"
    format: "webpage"
  - name: "Glenn Diesen"
    url: "https://www.youtube.com/@GDiesen1"
    type: "analysis"
    format: "youtube"
  - name: "Fadhel Kaboub"
    url: "https://globalsouthperspectives.substack.com/archive"
    type: "analysis"
    format: "webpage"
  - name: "Transnational Foundation"
    url: "https://thetransnational.substack.com/archive"
    type: "analysis"
    format: "webpage"
  - name: "People's Dispatch"
    url: "https://www.youtube.com/@PeoplesDispatch"
    type: "analysis"
    format: "youtube"
  - name: "Think BRICS"
    url: "https://www.youtube.com/@ThinkBRICS"
    type: "analysis"
    format: "youtube"
  - name: "Think BRICS"
    url: "https://thinkbrics.substack.com/archive"
    type: "analysis"
    format: "webpage"
  - name: "Thinkers Forum"
    url: "https://www.youtube.com/@thinkersforum4149"
    type: "analysis"
    format: "youtube"
  - name: "Diplomatify"
    url: "https://www.youtube.com/@dr.ilangokaruppannan"
    type: "analysis"
    format: "youtube"
  - name: "Neutrality Studies"
    url: "https://www.youtube.com/@neutralitystudies"
    type: "analysis"
    format: "youtube"
  - name: "Wave Media"
    url: "https://www.youtube.com/@wavemedia4433"
    type: "analysis"
    format: "youtube"
  - name: "Empire Files"
    url: "https://www.youtube.com/@EmpireFiles"
    type: "analysis"
    format: "youtube"
  - name: "Empire Watch"
    url: "https://www.youtube.com/@EmpireWatch"
    type: "analysis"
    format: "youtube"
  - name: "Double Down News"
    url: "https://www.youtube.com/@DoubleDownNews"
    type: "analysis"
    format: "youtube"
  - name: "DiEM25"
    url: "https://www.youtube.com/@DiEM25official"
    type: "analysis"
    format: "youtube"
  - name: "Electronic Intifada"
    url: "https://www.youtube.com/@TheElectronicIntifadas"
    type: "analysis"
    format: "youtube"
  - name: "FridayEveryday"
    url: "https://www.youtube.com/@Fridayeverydaycom"
    type: "analysis"
    format: "youtube"
  - name: "观察者网"
    url: "https://www.youtube.com/@guancha021"
    type: "analysis"
    format: "youtube"
  - name: "Global Times"
    url: "https://www.youtube.com/@globaltimes"
    type: "analysis"
    format: "youtube"
  - name: "China Up Close"
    url: "https://lijingjing.substack.com/archive"
    type: "analysis"
    format: "webpage"
  - name: "The China Academy"
    url: "https://chinaacademy.substack.com/archive"
    type: "analysis"
    format: "webpage"
  - name: "Reports on China"
    url: "https://www.youtube.com/@ReportsOnChina"
    type: "analysis"
    format: "youtube"
  - name: "Friends of Socialist China"
    url: "https://socialistchina.org"
    type: "analysis"
    format: "webpage"
  - name: "The China-Global South Project"
    url: "https://www.youtube.com/@chinaglobalsouth"
    type: "analysis"
    format: "youtube"
  - name: "Al Mayadeen English"
    url: "https://www.youtube.com/@almayadeenenglish"
    type: "analysis"
    format: "youtube"
  - name: "AJ+"
    url: "https://www.youtube.com/@ajplus"
    type: "analysis"
    format: "youtube"
  - name: "Jamarl Thomas"
    url: "https://www.youtube.com/@JamarlThomas"
    type: "analysis"
    format: "youtube"
  - name: "Bad Faith"
    url: "https://www.youtube.com/@BadFaithPodcast"
    type: "analysis"
    format: "youtube"
  - name: "Syriana Analysis"
    url: "https://www.youtube.com/@SyrianaAnalysis"
    type: "analysis"
    format: "youtube"
  - name: "The New Atlas"
    url: "https://www.youtube.com/@TheNewAtlas"
    type: "analysis"
    format: "youtube"
  # ------ Mainstream Sources ------
  - name: "TeleSUR English"
    url: "https://www.youtube.com/@telesurenglish"
    type: "datapoint"
    format: "youtube"
  - name: "Middle East Eye"
    url: "https://www.youtube.com/@MiddleEastEye"
    type: "datapoint"
    format: "youtube"
  - name: "Al Jazeera English"
    url: "https://www.youtube.com/@aljazeeraenglish"
    type: "datapoint"
    format: "youtube"
  - name: "Channel News Asia"
    url: "https://www.youtube.com/@channelnewsasia"
    type: "datapoint"
    format: "youtube"
  - name: "Channel News Asia Insider"
    url: "https://www.youtube.com/@CNAInsider"
    type: "datapoint"
    format: "youtube"
  - name: "Prime Minister's Office, Singaporea"
    url: "https://www.youtube.com/@pmosingapore"
    type: "datapoint"
    format: "youtube"
  - name: "South China Morning Post"
    url: "https://www.youtube.com/@SouthChinaMorningPost"
    type: "datapoint"
    format: "youtube"
  - name: "Straits Times"
    url: "https://www.youtube.com/@straitstimesonline"
    type: "datapoint"
    format: "youtube"
  - name: "CGTN"
    url: "https://www.youtube.com/@cgtn"
    type: "datapoint"
    format: "youtube"
  - name: "CGTN America"
    url: "https://www.youtube.com/@cgtnamerica"
    type: "datapoint"
    format: "youtube"
  - name: "CGTN Europe"
    url: "https://www.youtube.com/@CGTNEurope"
    type: "datapoint"
    format: "youtube"
  - name: "CGTN Africa"
    url: "https://www.youtube.com/@cgtnafrica"
    type: "datapoint"
    format: "youtube"
  - name: "TVP WORLD NEWS"
    url: "https://www.youtube.com/@TVPWorldNews"
    type: "datapoint"
    format: "youtube"
  - name: "Democracy Now!"
    url: "https://www.youtube.com/@DemocracyNow"
    type: "datapoint"
    format: "youtube"
